language: cpp

matrix:
    include:
        - os: linux
          dist: trusy
          sudo: false
          compiler: gcc
          addons:
            apt:
              packages:
                - qt5-default
                - qtbase5-dev-tools
                - qt5-qmake
                - qtmultimedia5-dev
                - libtag1-dev
                - libmediainfo-dev
                - libzen-dev
        - os: osx
          osx_image: xcode8.2
          compiler: clang

before_install:
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        brew update;
      fi

install:
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        brew update;
        brew install qt5;
        brew link --force qt5;
        brew install taglib;
        brew install mediainfo;
      fi

before_script:

script: 
    #- cd src/plugins/audiotag/ && qmake audiotag.pro && make
    - cd src/plugins/cleanup/ && qmake cleanup.pro && make
    - cd ../lyric/ && qmake lyric.pro && make
    - cd ../preparatory/ && qmake preparatory.pro && make
    - cd ../rename/ && qmake rename.pro && make
    - cd ../../ && qmake uman.pro && make
    - cd ../bin/wip/
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        if [ -r "UltraStarManager.app" ]; then
            macdeployqt UltraStarManager.app -dmg;
            link=$(curl --upload-file 'UltraStarManager.dmg' "https://transfer.sh/UltraStarManager-$(git rev-parse --short HEAD).dmg");
            echo "UltraStarManager.dmg should be available at:";
            echo "    $link";
        fi
      fi

notifications:
    email: false
