language: cpp

matrix:
    include:
        - os: linux
          dist: trusy
          sudo: required
          compiler: gcc
        - os: osx
          compiler: clang

before_install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        sudo apt-get -qy update;
      else
        brew update;
      fi

install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        sudo apt-get install qt5-default qtbase5-dev-tools qt5-qmake qtmultimedia5-dev libtag1-dev libmediainfo-dev libzen-dev;
      else
        brew update;
        brew install qt5;
        brew link --force qt5;
        brew install taglib;
        brew install mediainfo;
      fi
before_script:

script: 
    - cd src/plugins/audiotag/ && qmake audiotag.pro && make
    - cd ../cleanup/ && qmake cleanup.pro && make
    - cd ../lyric/ && qmake lyric.pro && make
    - cd ../preparatory/ && qmake preparatory.pro && make
    - cd ../rename/ && qmake rename.pro && make
    - cd ../../ && qmake uman.pro && make

notifications:
    email: false

#addons:
  #apt:
    #packages:
      #- qt5-default
      #- qtbase5-dev-tools
      #- qt5-qmake
      #- qtmultimedia5-dev
      #- libtag1-dev
      #- libmediainfo-dev
      #- libzen-dev
