language: cpp

matrix:
    fast_finish: true
    include:
        - os: linux
          dist: trusty
          sudo: false
          compiler: gcc
          addons:
            apt:
              packages:
                - qt5-default
                - qtbase5-dev-tools
                - qt5-qmake
                - qtmultimedia5-dev
                - libtag1-dev
                - libmediainfo-dev
                - libzen-dev
        - os: osx
          osx_image: xcode8.2
          compiler: clang
        - os: linux
          dist: trusty
          sudo: false
          compiler: ": w64"
          env: PLATFORM="mingw32" ARCH="x86_64" BITSIZE=64 HOST="x86_64"
          addons:
            apt:
              sources:
                - sourceline: 'ppa:tobydox/mingw-x-trusty'
              packages:
                - mingw-x-qt5base
                - mingw64-x-binutils
                - mingw64-x-gcc
                - mingw64-x-runtime
    allowed_failures:
        - env: PLATFORM="mingw32" ARCH="x86_64" BITSIZE=64 HOST="x86_64"

before_install:
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        brew update;
      fi

install:
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        brew install qt5;
        brew link --force qt5;
        brew install taglib;
        brew install mediainfo;
      fi

before_script:

script:
    - cd src/plugins/audiotag/ && qmake audiotag.pro && make
    - cd ../cleanup/ && qmake cleanup.pro && make
    - cd ../lyric/ && qmake lyric.pro && make
    - cd ../preparatory/ && qmake preparatory.pro && make
    - cd ../rename/ && qmake rename.pro && make
    - cd ../../ && qmake uman.pro && make
    - cd ../bin/release/
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        if [ -r "UltraStarManager.dmg" ]; then
            link=$(curl --upload-file 'UltraStarManager.dmg' "https://transfer.sh/UltraStarManager-$(git rev-parse --short HEAD).dmg");
            echo "UltraStarManager.dmg should be available at:";
            echo "    $link";
        fi
      fi

notifications:
    email: false
