language: cpp
os: linux
dist: trusty
sudo: false
before_install:
install:
before_script: cd src/
script: 
    - cd plugins/audiotag/ && qmake audiotag.pro && make
    - cd ../cleanup/ && qmake cleanup.pro && make
    - cd ../lyric/ && qmake lyric.pro && make
    - cd ../preparatory/ && qmake preparatory.pro && make
    - cd ../rename/ && qmake rename.pro && make
    - cd ../../ && qmake uman.pro && make
addons:
  apt:
    packages:
      - qt5-default
      - qtbase5-dev-tools
      - qt5-qmake
      - qtmultimedia5-dev
      - libtag1-dev
      - libmediainfo-dev
      - libzen-dev
