environment:
  QTDIR: C:\Qt\5.8\mingw53_32

install:
  - cmd: set PATH=%QTDIR%\bin;%QTDIR%\..\..\Tools\mingw530_32\bin;%PATH%

build_script:
  - cmd: >-
      cd src
      
      qmake uman.pro -spec win32-g++
      
      mingw32-make