environment:
  QTDIR: C:\Qt\5.8\mingw53_32

install:
  - cmd: set PATH=%QTDIR%\bin;%QTDIR%\..\..\Tools\mingw530_32\bin;%PATH%

build_script:
  - cmd: >-
      cd src/plugins/audiotag/
      
      qmake audiotag.pro -spec win32-g++
      
      mingw32-make
      
      cd ../cleanup/
      
      qmake cleanup.pro -spec win32-g++
      
      mingw32-make
      
      cd ../lyric/
      
      qmake lyric.pro -spec win32-g++
      
      mingw32-make
      
      cd ../preparatory/ 
      
      qmake preparatory.pro -spec win32-g++
      
      mingw32-make
      
      cd ../rename/
      
      qmake rename.pro -spec win32-g++
      
      mingw32-make
      
      cd ../../
      
      qmake uman.pro -spec win32-g++
      
      mingw32-make

artifacts:
  - path: bin/release
    name: UltraStar-Manager-portable
    type: zip
