environment:
  QTDIR: C:\Qt\5.8\mingw53_32

install:
  - set PATH=%QTDIR%\bin;%QTDIR%\..\..\Tools\mingw530_32\bin;C:\Program Files (x86)\NSIS\;%PATH%

build_script:
  - cd src/plugins/audiotag/
  - qmake audiotag.pro -spec win32-g++
  - mingw32-make -j4
  - cd ../cleanup/
  - qmake cleanup.pro -spec win32-g++
  - mingw32-make -j4
  - cd ../lyric/
  - qmake lyric.pro -spec win32-g++
  - mingw32-make -j4
  - cd ../preparatory/ 
  - qmake preparatory.pro -spec win32-g++
  - mingw32-make -j4
  - cd ../rename/
  - qmake rename.pro -spec win32-g++
  - mingw32-make -j4
  - cd ../../
  - qmake UltraStar-Manager.pro -spec win32-g++
  - mingw32-make -j4

after_build:
  - makensis ../setup/win32/UltraStar-Manager.nsi

artifacts:
  - path: bin/release
    name: UltraStar-Manager-portable
    type: zip
  - path: bin/UltraStar-Manager*-setup.exe
